all :	Ex1 Ex2 Ex3 Ex4 Ex5 Ex6 Ex7

pcode : PCode.c PCode.h
	gcc -c PCode.c

Ex1 :	pcode Ex1_pcode.c
	gcc -o Ex1 Ex1_pcode.c PCode.o

Ex2 :	pcode Ex2_pcode.c
	gcc -o Ex2 Ex2_pcode.c PCode.o

Ex3 :	pcode Ex3_pcode.c
	gcc -o Ex3 Ex3_pcode.c PCode.o

Ex4 :	pcode Ex4_pcode.c
	gcc -o Ex4 Ex4_pcode.c PCode.o

Ex5 :	pcode Ex5_pcode.c
	gcc -o Ex5 Ex5_pcode.c PCode.o

Ex6 :	pcode Ex6_pcode.c
	gcc -o Ex6 Ex6_pcode.c PCode.o

Ex7 :	pcode Ex7_pcode.c
	gcc -o Ex7 Ex7_pcode.c PCode.o

clean :
	rm -f *_pcode.c *.o
